version: '3'

services:
  backend-1:
    image: php:8.2-apache
    container_name: backend-1
    ports:
      - "9000:80"
    volumes:
      - ../backend:/var/www/html

  backend-2:
    image: php:8.2-apache
    container_name: backend-2
    ports:
      - "9001:80"
    volumes:
      - ../backend:/var/www/html

  backend-3:
    image: php:8.2-apache
    container_name: backend-3
    ports:
      - "9002:80"
    volumes:
      - ../backend:/var/www/html

  database:
    image: postgres:15-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kitsune
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: